### ISSUE TITLE
Svmap only detects Asterisk server

### ISSUE THREAD

**Issue by sakas23** [EnableSecurity/sipvicious#43]
Hello community,

I've install an asterisk server in a Ubuntu server virtual  machine.

I have also added two softphones, 1 to the virtual machine and 1 to the physical machine.

When i run svmap scanner with the command python svmap.py 192.168.0.0/24 it only shows the ipi of the Asterisk server.

Any help is much appreciated. 

Thanks in advance.

**Comment by sandrogauci** [comment]
Hi there - you didn't specify what your expected results are. Are you expecting  svmap to detect the softphones as well? If so, did you scan the port on which the soft phone is listening on? And how are the softphones configured?

I'm going to close since this does not appear to be a bug. If you reopen, please do specify what you're expecting from svmap and also the configuration of each system, what command you are running and so on.

**Comment by sakas23** [comment]
Hi sandro and thank you for your reply.

> 
> 
> Hi there - you didn't specify what your expected results are. Are you expecting svmap to detect the softphones as well? If so, did you scan the port on which the soft phone is listening on? And how are the softphones configured?
> 
> I'm going to close since this does not appear to be a bug. If you reopen, please do specify what you're expecting from svmap and also the configuration of each system, what command you are running and so on.

Hi sandro and thank you for your reply.

I expect to see the softphones too after the scan. 

The command i run was python svmap.py 192.168.0.0/24.

The softphones belong to SIP Users registered to Asterisk Server.

**Comment by sandrogauci** [comment]
It is likely that your softphones are listening on a random high port rather than the default port 5060 that is used by svmap. You may specify this port by using the `-p` flag. If the softphones are not using UDP (i.e. using TCP/TLS) then they might also be unreachable outside the TCP/TLS session. That would mean that svmap (or nmap) will not be able to detect it.

**Comment by sakas23** [comment]
> 
> 
> It is likely that your softphones are listening on a random high port rather than the default port 5060 that is used by svmap. You may specify this port by using the `-p` flag. If the softphones are not using UDP (i.e. using TCP/TLS) then they might also be unreachable outside the TCP/TLS session. That would mean that svmap (or nmap) will not be able to detect it.

The softphones use UDP protocol. Can i also specify a port range for scan option?

**Comment by sandrogauci** [comment]
yes

**Comment by sakas23** [comment]
> 
> 
> yes

So the command will be or example : python svmap.py 192.168.0.0/24 -p 10000-20000 ?

**Comment by sakas23** [comment]
Hello sandro,

Finally i managed to make svmap scan the softphones, but i specified the port in the command.

I tried to scan a port range 5000-65535 because the soft, but it takes so much time and it never finishes.

Is any way to make the scan faster?

And another thing is that sometimes the scan detects the softphones, sometimes it doesn't.

Thanks in advance.
