### ISSUE TITLE
svwar multi port support

### ISSUE THREAD

**Issue by gbiagomba** [EnableSecurity/sipvicious#64]
Hello,

While i was using svwar with the port flag it through up an error, i tried one port at a time and it liked that better. But i figured i let you know

```
"svwar -e100-200 127.0.0.1 -p 5060-5062,10000 -m INVITE"

Traceback (most recent call last):
  File "/usr/bin/svwar", line 11, in <module>
    load_entry_point('sipvicious==0.3.0', 'console_scripts', 'sipvicious_svwar')()
  File "/usr/share/sipvicious/sipvicious/svwar.py", line 601, in main
    sipvicious = TakeASip(
  File "/usr/share/sipvicious/sipvicious/svwar.py", line 86, in __init__
    self.dsthost, self.dstport = host, int(port)
ValueError: invalid literal for int() with base 10: '5060-5062,10000'
Traceback (most recent call last):
```

**Comment by 0xInfection** [comment]
Hi @gbiagomba,
Thanks for pulling this up, this seems like a bug, so will be rolling out a fix soon.

**Comment by sandrogauci** [comment]
Hi @gbiagomba thanks for noticing a 13 year old bug! Only `svmap` is meant to take port ranges (as it takes IP ranges too) - `svwar` and `svcrack` never really supported the functionality. Typically, you would want to identify a SIP device's IP and port using `svmap`, then use the other two tools for the attack phase.

So the bug is in the actual flag help, which is shared across all 3 tools but should actually be separated. We'll make two updates:

- separate the help for the port flag for each tool
- handle the `ValueError` exception

**Comment by 0xInfection** [comment]
#66 should do it. :)

**Comment by gbiagomba** [comment]
@sandrogauci was i the first to spot this out? i cant be lol

**Comment by sandrogauci** [comment]
@gbiagomba certainly first to complain about it :)

**Comment by gbiagomba** [comment]
Ohh wow lol
